name: Ruby

on:
  push:
    branches:
       -master
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ruby-mini-project"
          heroku_email: "anuragtechhub@gmail.com"
   
